export const META_DATA = {
  title: "Lava a Jato Lustosa",
  description:
    "Lava a Jato amplo e com rampa localizado no bairro Santa Etelvina, em Manaus. Oferece os seguintes serviços: lavagem simples e completa (com cera) para carros e motos, higienização interna, lavagem de motor, chassi e caixa de rodas. Tudo isso com qualidade, segurança e credibilidade 5 estrelas.",
  keywords: [
    "Lava jato",
    "Lava jato Manaus",
    "Lava a jato",
    "Lava a jato em Manaus",
    "Lava-jato",
    "Lava-jato em Manaus",
    "Lava-a-jato",
    "Lava-a-jato em Manaus",
    "Lava rápido",
    "Lava-rápido Manaus",
    "Lava a jato 24 horas",
    "Lava-jato 24 horas",
    "Ecolavagem",
    "Ecolavagem Manaus",
    "Ecolavagem Ponta Negra",
    "Eco-lavagem",
    "Lavagem de moto",
    "Lavagem de motor",
    "Lavagem de chassi",
    "Polimento em Manaus",
    "Higienização de carro",
    "Limpeza carro",
    "Lava jato centro",
    "Lava jato shopping",
    "Lava jato cachoeirinha",
    "Lava jato nova cidade",
    "Lava jato cidade nova",
    "Lava jato compensa",
    "Lava jato torres",
    "Lava jato tarumã",
    "Lava jato ponta negra",
    "Lava jato zona norte",
    "Lava jato zona leste",
  ],
  authorName: "Josué Lustosa - Desenvolvedor e Propietário",
  authorUrl: "https://josuelustosa.github.io/links/",
};
